import { FocusEvent, MouseEvent, Ref } from 'react';
import { IUseMenuButtonProps, IUseMenuItemProps, IUseMenuListProps, IUseMenuOptionGroupProps, IUseMenuOptionProps, IUseMenuProps } from './models';
export declare const MenuDescendantsProvider: import("react").Provider<import("../Descendants").DescendantsManager<HTMLElement, {}>>, useMenuDescendantsContext: () => import("../Descendants").DescendantsManager<HTMLElement, {}>, useMenuDescendants: () => import("../Descendants").DescendantsManager<HTMLElement, {}>, useMenuDescendant: (options?: {
    disabled?: boolean | undefined;
    id?: string | undefined;
} | undefined) => {
    descendants: import("../Descendants").DescendantsManager<HTMLElement, Record<string, any>>;
    index: number;
    enabledIndex: number;
    register: (node: HTMLElement | null) => void;
};
export type TUseMenuReturn = ReturnType<typeof useMenu>;
export declare const useMenu: (props?: IUseMenuProps) => {
    isOpen: boolean;
    onOpen: () => void;
    onClose: () => void;
    toggle: () => void;
    descendants: import("../Descendants").DescendantsManager<HTMLElement, {}>;
    isLazy: boolean | undefined;
    lazyBehavior: import("../../utils/methods/lazy").LazyMode | undefined;
    placement: import("@popperjs/core/lib/enums").ComputedPlacement;
    closeOnBlur: boolean | undefined;
    closeOnSelect: boolean;
    menuRef: import("react").RefObject<HTMLDivElement>;
    menuId: string;
    buttonId: string;
    overlay: {
        getOverlayProps: import("../../models").TPropGetter<Record<string, unknown>, import("../../models/types/prop-getter.type").TDOMAttributes<import("../../models/types/prop-getter.type").IDOMElement>>;
        getReferenceProps: import("../../models").TPropGetter<Record<string, unknown>, import("../../models/types/prop-getter.type").TDOMAttributes<import("../../models/types/prop-getter.type").IDOMElement>>;
        overlayRef: <T extends HTMLElement>(node: T | null) => void;
        referenceRef: <T_1 extends Element | import("@popperjs/core/lib/types").VirtualElement>(node: T_1 | null) => void;
        update(): void;
        forceUpdate(): void;
    };
    buttonRef: import("react").RefObject<HTMLButtonElement>;
};
export declare function useMenuButton(props?: IUseMenuButtonProps, externalRef?: Ref<HTMLElement>): {
    ref: (node: Element | import("@popperjs/core/lib/types").VirtualElement | null) => void;
    id: string;
    onClick: (event: MouseEvent<Element, globalThis.MouseEvent>) => void;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    autoFocus?: boolean | undefined;
    className?: string | undefined;
    contentEditable?: "inherit" | (boolean | "false" | "true") | "plaintext-only" | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: (boolean | "false" | "true") | undefined;
    enterKeyHint?: "next" | "search" | "enter" | "done" | "go" | "previous" | "send" | undefined;
    hidden?: boolean | undefined;
    lang?: string | undefined;
    nonce?: string | undefined;
    slot?: string | undefined;
    spellCheck?: (boolean | "false" | "true") | undefined;
    style?: import("react").CSSProperties | undefined;
    tabIndex?: number | undefined;
    title?: string | undefined;
    translate?: "yes" | "no" | undefined;
    radioGroup?: string | undefined;
    role?: import("react").AriaRole | undefined;
    about?: string | undefined;
    content?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    rel?: string | undefined;
    resource?: string | undefined;
    rev?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCapitalize?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    color?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "on" | "off" | undefined;
    inputMode?: "none" | "text" | "numeric" | "search" | "tel" | "url" | "email" | "decimal" | undefined;
    is?: string | undefined;
    "aria-activedescendant"?: string | undefined;
    "aria-atomic"?: (boolean | "false" | "true") | undefined;
    "aria-autocomplete"?: "both" | "none" | "inline" | "list" | undefined;
    "aria-braillelabel"?: string | undefined;
    "aria-brailleroledescription"?: string | undefined;
    "aria-busy"?: (boolean | "false" | "true") | undefined;
    "aria-checked"?: boolean | "mixed" | "false" | "true" | undefined;
    "aria-colcount"?: number | undefined;
    "aria-colindex"?: number | undefined;
    "aria-colindextext"?: string | undefined;
    "aria-colspan"?: number | undefined;
    "aria-controls"?: string | undefined;
    "aria-current"?: boolean | "page" | "false" | "true" | "time" | "step" | "location" | "date" | undefined;
    "aria-describedby"?: string | undefined;
    "aria-description"?: string | undefined;
    "aria-details"?: string | undefined;
    "aria-disabled"?: (boolean | "false" | "true") | undefined;
    "aria-dropeffect"?: "none" | "copy" | "move" | "link" | "execute" | "popup" | undefined;
    "aria-errormessage"?: string | undefined;
    "aria-expanded"?: (boolean | "false" | "true") | undefined;
    "aria-flowto"?: string | undefined;
    "aria-grabbed"?: (boolean | "false" | "true") | undefined;
    "aria-haspopup"?: boolean | "listbox" | "grid" | "menu" | "false" | "true" | "dialog" | "tree" | undefined;
    "aria-hidden"?: (boolean | "false" | "true") | undefined;
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
    "aria-keyshortcuts"?: string | undefined;
    "aria-label"?: string | undefined;
    "aria-labelledby"?: string | undefined;
    "aria-level"?: number | undefined;
    "aria-live"?: "off" | "assertive" | "polite" | undefined;
    "aria-modal"?: (boolean | "false" | "true") | undefined;
    "aria-multiline"?: (boolean | "false" | "true") | undefined;
    "aria-multiselectable"?: (boolean | "false" | "true") | undefined;
    "aria-orientation"?: "horizontal" | "vertical" | undefined;
    "aria-owns"?: string | undefined;
    "aria-placeholder"?: string | undefined;
    "aria-posinset"?: number | undefined;
    "aria-pressed"?: boolean | "mixed" | "false" | "true" | undefined;
    "aria-readonly"?: (boolean | "false" | "true") | undefined;
    "aria-relevant"?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
    "aria-required"?: (boolean | "false" | "true") | undefined;
    "aria-roledescription"?: string | undefined;
    "aria-rowcount"?: number | undefined;
    "aria-rowindex"?: number | undefined;
    "aria-rowindextext"?: string | undefined;
    "aria-rowspan"?: number | undefined;
    "aria-selected"?: (boolean | "false" | "true") | undefined;
    "aria-setsize"?: number | undefined;
    "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
    "aria-valuemax"?: number | undefined;
    "aria-valuemin"?: number | undefined;
    "aria-valuenow"?: number | undefined;
    "aria-valuetext"?: string | undefined;
    children?: import("react").ReactNode;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: import("react").ClipboardEventHandler<Element> | undefined;
    onCopyCapture?: import("react").ClipboardEventHandler<Element> | undefined;
    onCut?: import("react").ClipboardEventHandler<Element> | undefined;
    onCutCapture?: import("react").ClipboardEventHandler<Element> | undefined;
    onPaste?: import("react").ClipboardEventHandler<Element> | undefined;
    onPasteCapture?: import("react").ClipboardEventHandler<Element> | undefined;
    onCompositionEnd?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionEndCapture?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionStart?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionStartCapture?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionUpdate?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionUpdateCapture?: import("react").CompositionEventHandler<Element> | undefined;
    onFocus?: import("react").FocusEventHandler<Element> | undefined;
    onFocusCapture?: import("react").FocusEventHandler<Element> | undefined;
    onBlur?: import("react").FocusEventHandler<Element> | undefined;
    onBlurCapture?: import("react").FocusEventHandler<Element> | undefined;
    onChange?: import("react").FormEventHandler<Element> | undefined;
    onChangeCapture?: import("react").FormEventHandler<Element> | undefined;
    onBeforeInput?: import("react").FormEventHandler<Element> | undefined;
    onBeforeInputCapture?: import("react").FormEventHandler<Element> | undefined;
    onInput?: import("react").FormEventHandler<Element> | undefined;
    onInputCapture?: import("react").FormEventHandler<Element> | undefined;
    onReset?: import("react").FormEventHandler<Element> | undefined;
    onResetCapture?: import("react").FormEventHandler<Element> | undefined;
    onSubmit?: import("react").FormEventHandler<Element> | undefined;
    onSubmitCapture?: import("react").FormEventHandler<Element> | undefined;
    onInvalid?: import("react").FormEventHandler<Element> | undefined;
    onInvalidCapture?: import("react").FormEventHandler<Element> | undefined;
    onLoad?: import("react").ReactEventHandler<Element> | undefined;
    onLoadCapture?: import("react").ReactEventHandler<Element> | undefined;
    onError?: import("react").ReactEventHandler<Element> | undefined;
    onErrorCapture?: import("react").ReactEventHandler<Element> | undefined;
    onKeyDown?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyDownCapture?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyPress?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyPressCapture?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyUp?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyUpCapture?: import("react").KeyboardEventHandler<Element> | undefined;
    onAbort?: import("react").ReactEventHandler<Element> | undefined;
    onAbortCapture?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlay?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlayCapture?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlayThrough?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlayThroughCapture?: import("react").ReactEventHandler<Element> | undefined;
    onDurationChange?: import("react").ReactEventHandler<Element> | undefined;
    onDurationChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onEmptied?: import("react").ReactEventHandler<Element> | undefined;
    onEmptiedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onEncrypted?: import("react").ReactEventHandler<Element> | undefined;
    onEncryptedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onEnded?: import("react").ReactEventHandler<Element> | undefined;
    onEndedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedData?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedDataCapture?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedMetadata?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedMetadataCapture?: import("react").ReactEventHandler<Element> | undefined;
    onLoadStart?: import("react").ReactEventHandler<Element> | undefined;
    onLoadStartCapture?: import("react").ReactEventHandler<Element> | undefined;
    onPause?: import("react").ReactEventHandler<Element> | undefined;
    onPauseCapture?: import("react").ReactEventHandler<Element> | undefined;
    onPlay?: import("react").ReactEventHandler<Element> | undefined;
    onPlayCapture?: import("react").ReactEventHandler<Element> | undefined;
    onPlaying?: import("react").ReactEventHandler<Element> | undefined;
    onPlayingCapture?: import("react").ReactEventHandler<Element> | undefined;
    onProgress?: import("react").ReactEventHandler<Element> | undefined;
    onProgressCapture?: import("react").ReactEventHandler<Element> | undefined;
    onRateChange?: import("react").ReactEventHandler<Element> | undefined;
    onRateChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onResize?: import("react").ReactEventHandler<Element> | undefined;
    onResizeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onSeeked?: import("react").ReactEventHandler<Element> | undefined;
    onSeekedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onSeeking?: import("react").ReactEventHandler<Element> | undefined;
    onSeekingCapture?: import("react").ReactEventHandler<Element> | undefined;
    onStalled?: import("react").ReactEventHandler<Element> | undefined;
    onStalledCapture?: import("react").ReactEventHandler<Element> | undefined;
    onSuspend?: import("react").ReactEventHandler<Element> | undefined;
    onSuspendCapture?: import("react").ReactEventHandler<Element> | undefined;
    onTimeUpdate?: import("react").ReactEventHandler<Element> | undefined;
    onTimeUpdateCapture?: import("react").ReactEventHandler<Element> | undefined;
    onVolumeChange?: import("react").ReactEventHandler<Element> | undefined;
    onVolumeChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onWaiting?: import("react").ReactEventHandler<Element> | undefined;
    onWaitingCapture?: import("react").ReactEventHandler<Element> | undefined;
    onAuxClick?: import("react").MouseEventHandler<Element> | undefined;
    onAuxClickCapture?: import("react").MouseEventHandler<Element> | undefined;
    onClickCapture?: import("react").MouseEventHandler<Element> | undefined;
    onContextMenu?: import("react").MouseEventHandler<Element> | undefined;
    onContextMenuCapture?: import("react").MouseEventHandler<Element> | undefined;
    onDoubleClick?: import("react").MouseEventHandler<Element> | undefined;
    onDoubleClickCapture?: import("react").MouseEventHandler<Element> | undefined;
    onDrag?: import("react").DragEventHandler<Element> | undefined;
    onDragCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragEnd?: import("react").DragEventHandler<Element> | undefined;
    onDragEndCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragEnter?: import("react").DragEventHandler<Element> | undefined;
    onDragEnterCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragExit?: import("react").DragEventHandler<Element> | undefined;
    onDragExitCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragLeave?: import("react").DragEventHandler<Element> | undefined;
    onDragLeaveCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragOver?: import("react").DragEventHandler<Element> | undefined;
    onDragOverCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragStart?: import("react").DragEventHandler<Element> | undefined;
    onDragStartCapture?: import("react").DragEventHandler<Element> | undefined;
    onDrop?: import("react").DragEventHandler<Element> | undefined;
    onDropCapture?: import("react").DragEventHandler<Element> | undefined;
    onMouseDown?: import("react").MouseEventHandler<Element> | undefined;
    onMouseDownCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseEnter?: import("react").MouseEventHandler<Element> | undefined;
    onMouseLeave?: import("react").MouseEventHandler<Element> | undefined;
    onMouseMove?: import("react").MouseEventHandler<Element> | undefined;
    onMouseMoveCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOut?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOutCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOver?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOverCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseUp?: import("react").MouseEventHandler<Element> | undefined;
    onMouseUpCapture?: import("react").MouseEventHandler<Element> | undefined;
    onSelect?: import("react").ReactEventHandler<Element> | undefined;
    onSelectCapture?: import("react").ReactEventHandler<Element> | undefined;
    onTouchCancel?: import("react").TouchEventHandler<Element> | undefined;
    onTouchCancelCapture?: import("react").TouchEventHandler<Element> | undefined;
    onTouchEnd?: import("react").TouchEventHandler<Element> | undefined;
    onTouchEndCapture?: import("react").TouchEventHandler<Element> | undefined;
    onTouchMove?: import("react").TouchEventHandler<Element> | undefined;
    onTouchMoveCapture?: import("react").TouchEventHandler<Element> | undefined;
    onTouchStart?: import("react").TouchEventHandler<Element> | undefined;
    onTouchStartCapture?: import("react").TouchEventHandler<Element> | undefined;
    onPointerDown?: import("react").PointerEventHandler<Element> | undefined;
    onPointerDownCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerMove?: import("react").PointerEventHandler<Element> | undefined;
    onPointerMoveCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerUp?: import("react").PointerEventHandler<Element> | undefined;
    onPointerUpCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerCancel?: import("react").PointerEventHandler<Element> | undefined;
    onPointerCancelCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerEnter?: import("react").PointerEventHandler<Element> | undefined;
    onPointerLeave?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOver?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOverCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOut?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOutCapture?: import("react").PointerEventHandler<Element> | undefined;
    onGotPointerCapture?: import("react").PointerEventHandler<Element> | undefined;
    onGotPointerCaptureCapture?: import("react").PointerEventHandler<Element> | undefined;
    onLostPointerCapture?: import("react").PointerEventHandler<Element> | undefined;
    onLostPointerCaptureCapture?: import("react").PointerEventHandler<Element> | undefined;
    onScroll?: import("react").UIEventHandler<Element> | undefined;
    onScrollCapture?: import("react").UIEventHandler<Element> | undefined;
    onWheel?: import("react").WheelEventHandler<Element> | undefined;
    onWheelCapture?: import("react").WheelEventHandler<Element> | undefined;
    onAnimationStart?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationStartCapture?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationEnd?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationEndCapture?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationIteration?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationIterationCapture?: import("react").AnimationEventHandler<Element> | undefined;
    onTransitionEnd?: import("react").TransitionEventHandler<Element> | undefined;
    onTransitionEndCapture?: import("react").TransitionEventHandler<Element> | undefined;
};
export declare function useMenuList(props?: IUseMenuListProps, ref?: Ref<any>): {
    htmlProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: "inherit" | (boolean | "false" | "true") | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "false" | "true") | undefined;
        enterKeyHint?: "next" | "search" | "enter" | "done" | "go" | "previous" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "false" | "true") | undefined;
        style?: import("react").CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: import("react").AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCapitalize?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "numeric" | "search" | "tel" | "url" | "email" | "decimal" | undefined;
        is?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "false" | "true") | undefined;
        "aria-autocomplete"?: "both" | "none" | "inline" | "list" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "false" | "true") | undefined;
        "aria-checked"?: boolean | "mixed" | "false" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "page" | "false" | "true" | "time" | "step" | "location" | "date" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "false" | "true") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "move" | "link" | "execute" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "false" | "true") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "false" | "true") | undefined;
        "aria-haspopup"?: boolean | "listbox" | "grid" | "menu" | "false" | "true" | "dialog" | "tree" | undefined;
        "aria-hidden"?: (boolean | "false" | "true") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "false" | "true") | undefined;
        "aria-multiline"?: (boolean | "false" | "true") | undefined;
        "aria-multiselectable"?: (boolean | "false" | "true") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "mixed" | "false" | "true" | undefined;
        "aria-readonly"?: (boolean | "false" | "true") | undefined;
        "aria-relevant"?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "false" | "true") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "false" | "true") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: import("react").ClipboardEventHandler<Element> | undefined;
        onCopyCapture?: import("react").ClipboardEventHandler<Element> | undefined;
        onCut?: import("react").ClipboardEventHandler<Element> | undefined;
        onCutCapture?: import("react").ClipboardEventHandler<Element> | undefined;
        onPaste?: import("react").ClipboardEventHandler<Element> | undefined;
        onPasteCapture?: import("react").ClipboardEventHandler<Element> | undefined;
        onCompositionEnd?: import("react").CompositionEventHandler<Element> | undefined;
        onCompositionEndCapture?: import("react").CompositionEventHandler<Element> | undefined;
        onCompositionStart?: import("react").CompositionEventHandler<Element> | undefined;
        onCompositionStartCapture?: import("react").CompositionEventHandler<Element> | undefined;
        onCompositionUpdate?: import("react").CompositionEventHandler<Element> | undefined;
        onCompositionUpdateCapture?: import("react").CompositionEventHandler<Element> | undefined;
        onFocus?: import("react").FocusEventHandler<Element> | undefined;
        onFocusCapture?: import("react").FocusEventHandler<Element> | undefined;
        onBlur?: import("react").FocusEventHandler<Element> | undefined;
        onBlurCapture?: import("react").FocusEventHandler<Element> | undefined;
        onChange?: import("react").FormEventHandler<Element> | undefined;
        onChangeCapture?: import("react").FormEventHandler<Element> | undefined;
        onBeforeInput?: import("react").FormEventHandler<Element> | undefined;
        onBeforeInputCapture?: import("react").FormEventHandler<Element> | undefined;
        onInput?: import("react").FormEventHandler<Element> | undefined;
        onInputCapture?: import("react").FormEventHandler<Element> | undefined;
        onReset?: import("react").FormEventHandler<Element> | undefined;
        onResetCapture?: import("react").FormEventHandler<Element> | undefined;
        onSubmit?: import("react").FormEventHandler<Element> | undefined;
        onSubmitCapture?: import("react").FormEventHandler<Element> | undefined;
        onInvalid?: import("react").FormEventHandler<Element> | undefined;
        onInvalidCapture?: import("react").FormEventHandler<Element> | undefined;
        onLoad?: import("react").ReactEventHandler<Element> | undefined;
        onLoadCapture?: import("react").ReactEventHandler<Element> | undefined;
        onError?: import("react").ReactEventHandler<Element> | undefined;
        onErrorCapture?: import("react").ReactEventHandler<Element> | undefined;
        onKeyDown?: import("react").KeyboardEventHandler<Element> | undefined;
        onKeyDownCapture?: import("react").KeyboardEventHandler<Element> | undefined;
        onKeyPress?: import("react").KeyboardEventHandler<Element> | undefined;
        onKeyPressCapture?: import("react").KeyboardEventHandler<Element> | undefined;
        onKeyUp?: import("react").KeyboardEventHandler<Element> | undefined;
        onKeyUpCapture?: import("react").KeyboardEventHandler<Element> | undefined;
        onAbort?: import("react").ReactEventHandler<Element> | undefined;
        onAbortCapture?: import("react").ReactEventHandler<Element> | undefined;
        onCanPlay?: import("react").ReactEventHandler<Element> | undefined;
        onCanPlayCapture?: import("react").ReactEventHandler<Element> | undefined;
        onCanPlayThrough?: import("react").ReactEventHandler<Element> | undefined;
        onCanPlayThroughCapture?: import("react").ReactEventHandler<Element> | undefined;
        onDurationChange?: import("react").ReactEventHandler<Element> | undefined;
        onDurationChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
        onEmptied?: import("react").ReactEventHandler<Element> | undefined;
        onEmptiedCapture?: import("react").ReactEventHandler<Element> | undefined;
        onEncrypted?: import("react").ReactEventHandler<Element> | undefined;
        onEncryptedCapture?: import("react").ReactEventHandler<Element> | undefined;
        onEnded?: import("react").ReactEventHandler<Element> | undefined;
        onEndedCapture?: import("react").ReactEventHandler<Element> | undefined;
        onLoadedData?: import("react").ReactEventHandler<Element> | undefined;
        onLoadedDataCapture?: import("react").ReactEventHandler<Element> | undefined;
        onLoadedMetadata?: import("react").ReactEventHandler<Element> | undefined;
        onLoadedMetadataCapture?: import("react").ReactEventHandler<Element> | undefined;
        onLoadStart?: import("react").ReactEventHandler<Element> | undefined;
        onLoadStartCapture?: import("react").ReactEventHandler<Element> | undefined;
        onPause?: import("react").ReactEventHandler<Element> | undefined;
        onPauseCapture?: import("react").ReactEventHandler<Element> | undefined;
        onPlay?: import("react").ReactEventHandler<Element> | undefined;
        onPlayCapture?: import("react").ReactEventHandler<Element> | undefined;
        onPlaying?: import("react").ReactEventHandler<Element> | undefined;
        onPlayingCapture?: import("react").ReactEventHandler<Element> | undefined;
        onProgress?: import("react").ReactEventHandler<Element> | undefined;
        onProgressCapture?: import("react").ReactEventHandler<Element> | undefined;
        onRateChange?: import("react").ReactEventHandler<Element> | undefined;
        onRateChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
        onResize?: import("react").ReactEventHandler<Element> | undefined;
        onResizeCapture?: import("react").ReactEventHandler<Element> | undefined;
        onSeeked?: import("react").ReactEventHandler<Element> | undefined;
        onSeekedCapture?: import("react").ReactEventHandler<Element> | undefined;
        onSeeking?: import("react").ReactEventHandler<Element> | undefined;
        onSeekingCapture?: import("react").ReactEventHandler<Element> | undefined;
        onStalled?: import("react").ReactEventHandler<Element> | undefined;
        onStalledCapture?: import("react").ReactEventHandler<Element> | undefined;
        onSuspend?: import("react").ReactEventHandler<Element> | undefined;
        onSuspendCapture?: import("react").ReactEventHandler<Element> | undefined;
        onTimeUpdate?: import("react").ReactEventHandler<Element> | undefined;
        onTimeUpdateCapture?: import("react").ReactEventHandler<Element> | undefined;
        onVolumeChange?: import("react").ReactEventHandler<Element> | undefined;
        onVolumeChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
        onWaiting?: import("react").ReactEventHandler<Element> | undefined;
        onWaitingCapture?: import("react").ReactEventHandler<Element> | undefined;
        onAuxClick?: import("react").MouseEventHandler<Element> | undefined;
        onAuxClickCapture?: import("react").MouseEventHandler<Element> | undefined;
        onClick?: import("react").MouseEventHandler<Element> | undefined;
        onClickCapture?: import("react").MouseEventHandler<Element> | undefined;
        onContextMenu?: import("react").MouseEventHandler<Element> | undefined;
        onContextMenuCapture?: import("react").MouseEventHandler<Element> | undefined;
        onDoubleClick?: import("react").MouseEventHandler<Element> | undefined;
        onDoubleClickCapture?: import("react").MouseEventHandler<Element> | undefined;
        onDrag?: import("react").DragEventHandler<Element> | undefined;
        onDragCapture?: import("react").DragEventHandler<Element> | undefined;
        onDragEnd?: import("react").DragEventHandler<Element> | undefined;
        onDragEndCapture?: import("react").DragEventHandler<Element> | undefined;
        onDragEnter?: import("react").DragEventHandler<Element> | undefined;
        onDragEnterCapture?: import("react").DragEventHandler<Element> | undefined;
        onDragExit?: import("react").DragEventHandler<Element> | undefined;
        onDragExitCapture?: import("react").DragEventHandler<Element> | undefined;
        onDragLeave?: import("react").DragEventHandler<Element> | undefined;
        onDragLeaveCapture?: import("react").DragEventHandler<Element> | undefined;
        onDragOver?: import("react").DragEventHandler<Element> | undefined;
        onDragOverCapture?: import("react").DragEventHandler<Element> | undefined;
        onDragStart?: import("react").DragEventHandler<Element> | undefined;
        onDragStartCapture?: import("react").DragEventHandler<Element> | undefined;
        onDrop?: import("react").DragEventHandler<Element> | undefined;
        onDropCapture?: import("react").DragEventHandler<Element> | undefined;
        onMouseDown?: import("react").MouseEventHandler<Element> | undefined;
        onMouseDownCapture?: import("react").MouseEventHandler<Element> | undefined;
        onMouseEnter?: import("react").MouseEventHandler<Element> | undefined;
        onMouseLeave?: import("react").MouseEventHandler<Element> | undefined;
        onMouseMove?: import("react").MouseEventHandler<Element> | undefined;
        onMouseMoveCapture?: import("react").MouseEventHandler<Element> | undefined;
        onMouseOut?: import("react").MouseEventHandler<Element> | undefined;
        onMouseOutCapture?: import("react").MouseEventHandler<Element> | undefined;
        onMouseOver?: import("react").MouseEventHandler<Element> | undefined;
        onMouseOverCapture?: import("react").MouseEventHandler<Element> | undefined;
        onMouseUp?: import("react").MouseEventHandler<Element> | undefined;
        onMouseUpCapture?: import("react").MouseEventHandler<Element> | undefined;
        onSelect?: import("react").ReactEventHandler<Element> | undefined;
        onSelectCapture?: import("react").ReactEventHandler<Element> | undefined;
        onTouchCancel?: import("react").TouchEventHandler<Element> | undefined;
        onTouchCancelCapture?: import("react").TouchEventHandler<Element> | undefined;
        onTouchEnd?: import("react").TouchEventHandler<Element> | undefined;
        onTouchEndCapture?: import("react").TouchEventHandler<Element> | undefined;
        onTouchMove?: import("react").TouchEventHandler<Element> | undefined;
        onTouchMoveCapture?: import("react").TouchEventHandler<Element> | undefined;
        onTouchStart?: import("react").TouchEventHandler<Element> | undefined;
        onTouchStartCapture?: import("react").TouchEventHandler<Element> | undefined;
        onPointerDown?: import("react").PointerEventHandler<Element> | undefined;
        onPointerDownCapture?: import("react").PointerEventHandler<Element> | undefined;
        onPointerMove?: import("react").PointerEventHandler<Element> | undefined;
        onPointerMoveCapture?: import("react").PointerEventHandler<Element> | undefined;
        onPointerUp?: import("react").PointerEventHandler<Element> | undefined;
        onPointerUpCapture?: import("react").PointerEventHandler<Element> | undefined;
        onPointerCancel?: import("react").PointerEventHandler<Element> | undefined;
        onPointerCancelCapture?: import("react").PointerEventHandler<Element> | undefined;
        onPointerEnter?: import("react").PointerEventHandler<Element> | undefined;
        onPointerLeave?: import("react").PointerEventHandler<Element> | undefined;
        onPointerOver?: import("react").PointerEventHandler<Element> | undefined;
        onPointerOverCapture?: import("react").PointerEventHandler<Element> | undefined;
        onPointerOut?: import("react").PointerEventHandler<Element> | undefined;
        onPointerOutCapture?: import("react").PointerEventHandler<Element> | undefined;
        onGotPointerCapture?: import("react").PointerEventHandler<Element> | undefined;
        onGotPointerCaptureCapture?: import("react").PointerEventHandler<Element> | undefined;
        onLostPointerCapture?: import("react").PointerEventHandler<Element> | undefined;
        onLostPointerCaptureCapture?: import("react").PointerEventHandler<Element> | undefined;
        onScroll?: import("react").UIEventHandler<Element> | undefined;
        onScrollCapture?: import("react").UIEventHandler<Element> | undefined;
        onWheel?: import("react").WheelEventHandler<Element> | undefined;
        onWheelCapture?: import("react").WheelEventHandler<Element> | undefined;
        onAnimationStart?: import("react").AnimationEventHandler<Element> | undefined;
        onAnimationStartCapture?: import("react").AnimationEventHandler<Element> | undefined;
        onAnimationEnd?: import("react").AnimationEventHandler<Element> | undefined;
        onAnimationEndCapture?: import("react").AnimationEventHandler<Element> | undefined;
        onAnimationIteration?: import("react").AnimationEventHandler<Element> | undefined;
        onAnimationIterationCapture?: import("react").AnimationEventHandler<Element> | undefined;
        onTransitionEnd?: import("react").TransitionEventHandler<Element> | undefined;
        onTransitionEndCapture?: import("react").TransitionEventHandler<Element> | undefined;
    };
    animation: string;
    show: boolean;
    beforeEnter: () => void;
    overlayProps: import("react").AriaAttributes & import("react").DOMAttributes<import("../../models/types/prop-getter.type").IDOMElement> & import("../../models/types/prop-getter.type").IDataAttributes & {
        id?: string | undefined;
        role?: import("react").AriaRole | undefined;
        tabIndex?: number | undefined;
        style?: import("react").CSSProperties | undefined;
    } & import("react").RefAttributes<any>;
    children: import("react").ReactNode;
    tabIndex: number;
    id: string;
};
export declare function useMenuItem(props?: IUseMenuItemProps, externalRef?: Ref<any>): {
    onClick: (event: MouseEvent) => void;
    onFocus: (event: FocusEvent) => void;
    onMouseEnter: (event: MouseEvent) => void;
    onMouseMove: (event: MouseEvent) => void;
    onMouseLeave: (event: MouseEvent) => void;
    ref: (node: any) => void;
    disabled: boolean | undefined;
    type: "button" | "reset" | "submit";
    id: string;
    tabIndex: number;
    hidden?: boolean | undefined;
    content?: string | undefined;
    style?: import("react").CSSProperties | undefined;
    translate?: "yes" | "no" | undefined;
    slot?: string | undefined;
    title?: string | undefined;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    autoFocus?: boolean | undefined;
    className?: string | undefined;
    contentEditable?: "inherit" | (boolean | "false" | "true") | "plaintext-only" | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: (boolean | "false" | "true") | undefined;
    enterKeyHint?: "next" | "search" | "enter" | "done" | "go" | "previous" | "send" | undefined;
    lang?: string | undefined;
    nonce?: string | undefined;
    spellCheck?: (boolean | "false" | "true") | undefined;
    radioGroup?: string | undefined;
    role?: import("react").AriaRole | undefined;
    about?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    rel?: string | undefined;
    resource?: string | undefined;
    rev?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCapitalize?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "on" | "off" | undefined;
    inputMode?: "none" | "text" | "numeric" | "search" | "tel" | "url" | "email" | "decimal" | undefined;
    is?: string | undefined;
    "aria-activedescendant"?: string | undefined;
    "aria-atomic"?: (boolean | "false" | "true") | undefined;
    "aria-autocomplete"?: "both" | "none" | "inline" | "list" | undefined;
    "aria-braillelabel"?: string | undefined;
    "aria-brailleroledescription"?: string | undefined;
    "aria-busy"?: (boolean | "false" | "true") | undefined;
    "aria-checked"?: boolean | "mixed" | "false" | "true" | undefined;
    "aria-colcount"?: number | undefined;
    "aria-colindex"?: number | undefined;
    "aria-colindextext"?: string | undefined;
    "aria-colspan"?: number | undefined;
    "aria-controls"?: string | undefined;
    "aria-current"?: boolean | "page" | "false" | "true" | "time" | "step" | "location" | "date" | undefined;
    "aria-describedby"?: string | undefined;
    "aria-description"?: string | undefined;
    "aria-details"?: string | undefined;
    "aria-disabled"?: (boolean | "false" | "true") | undefined;
    "aria-dropeffect"?: "none" | "copy" | "move" | "link" | "execute" | "popup" | undefined;
    "aria-errormessage"?: string | undefined;
    "aria-expanded"?: (boolean | "false" | "true") | undefined;
    "aria-flowto"?: string | undefined;
    "aria-grabbed"?: (boolean | "false" | "true") | undefined;
    "aria-haspopup"?: boolean | "listbox" | "grid" | "menu" | "false" | "true" | "dialog" | "tree" | undefined;
    "aria-hidden"?: (boolean | "false" | "true") | undefined;
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
    "aria-keyshortcuts"?: string | undefined;
    "aria-label"?: string | undefined;
    "aria-labelledby"?: string | undefined;
    "aria-level"?: number | undefined;
    "aria-live"?: "off" | "assertive" | "polite" | undefined;
    "aria-modal"?: (boolean | "false" | "true") | undefined;
    "aria-multiline"?: (boolean | "false" | "true") | undefined;
    "aria-multiselectable"?: (boolean | "false" | "true") | undefined;
    "aria-orientation"?: "horizontal" | "vertical" | undefined;
    "aria-owns"?: string | undefined;
    "aria-placeholder"?: string | undefined;
    "aria-posinset"?: number | undefined;
    "aria-pressed"?: boolean | "mixed" | "false" | "true" | undefined;
    "aria-readonly"?: (boolean | "false" | "true") | undefined;
    "aria-relevant"?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
    "aria-required"?: (boolean | "false" | "true") | undefined;
    "aria-roledescription"?: string | undefined;
    "aria-rowcount"?: number | undefined;
    "aria-rowindex"?: number | undefined;
    "aria-rowindextext"?: string | undefined;
    "aria-rowspan"?: number | undefined;
    "aria-selected"?: (boolean | "false" | "true") | undefined;
    "aria-setsize"?: number | undefined;
    "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
    "aria-valuemax"?: number | undefined;
    "aria-valuemin"?: number | undefined;
    "aria-valuenow"?: number | undefined;
    "aria-valuetext"?: string | undefined;
    children?: import("react").ReactNode;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: import("react").ClipboardEventHandler<Element> | undefined;
    onCopyCapture?: import("react").ClipboardEventHandler<Element> | undefined;
    onCut?: import("react").ClipboardEventHandler<Element> | undefined;
    onCutCapture?: import("react").ClipboardEventHandler<Element> | undefined;
    onPaste?: import("react").ClipboardEventHandler<Element> | undefined;
    onPasteCapture?: import("react").ClipboardEventHandler<Element> | undefined;
    onCompositionEnd?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionEndCapture?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionStart?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionStartCapture?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionUpdate?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionUpdateCapture?: import("react").CompositionEventHandler<Element> | undefined;
    onFocusCapture?: import("react").FocusEventHandler<Element> | undefined;
    onBlur?: import("react").FocusEventHandler<Element> | undefined;
    onBlurCapture?: import("react").FocusEventHandler<Element> | undefined;
    onChange?: import("react").FormEventHandler<Element> | undefined;
    onChangeCapture?: import("react").FormEventHandler<Element> | undefined;
    onBeforeInput?: import("react").FormEventHandler<Element> | undefined;
    onBeforeInputCapture?: import("react").FormEventHandler<Element> | undefined;
    onInput?: import("react").FormEventHandler<Element> | undefined;
    onInputCapture?: import("react").FormEventHandler<Element> | undefined;
    onReset?: import("react").FormEventHandler<Element> | undefined;
    onResetCapture?: import("react").FormEventHandler<Element> | undefined;
    onSubmit?: import("react").FormEventHandler<Element> | undefined;
    onSubmitCapture?: import("react").FormEventHandler<Element> | undefined;
    onInvalid?: import("react").FormEventHandler<Element> | undefined;
    onInvalidCapture?: import("react").FormEventHandler<Element> | undefined;
    onLoad?: import("react").ReactEventHandler<Element> | undefined;
    onLoadCapture?: import("react").ReactEventHandler<Element> | undefined;
    onError?: import("react").ReactEventHandler<Element> | undefined;
    onErrorCapture?: import("react").ReactEventHandler<Element> | undefined;
    onKeyDown?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyDownCapture?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyPress?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyPressCapture?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyUp?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyUpCapture?: import("react").KeyboardEventHandler<Element> | undefined;
    onAbort?: import("react").ReactEventHandler<Element> | undefined;
    onAbortCapture?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlay?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlayCapture?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlayThrough?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlayThroughCapture?: import("react").ReactEventHandler<Element> | undefined;
    onDurationChange?: import("react").ReactEventHandler<Element> | undefined;
    onDurationChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onEmptied?: import("react").ReactEventHandler<Element> | undefined;
    onEmptiedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onEncrypted?: import("react").ReactEventHandler<Element> | undefined;
    onEncryptedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onEnded?: import("react").ReactEventHandler<Element> | undefined;
    onEndedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedData?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedDataCapture?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedMetadata?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedMetadataCapture?: import("react").ReactEventHandler<Element> | undefined;
    onLoadStart?: import("react").ReactEventHandler<Element> | undefined;
    onLoadStartCapture?: import("react").ReactEventHandler<Element> | undefined;
    onPause?: import("react").ReactEventHandler<Element> | undefined;
    onPauseCapture?: import("react").ReactEventHandler<Element> | undefined;
    onPlay?: import("react").ReactEventHandler<Element> | undefined;
    onPlayCapture?: import("react").ReactEventHandler<Element> | undefined;
    onPlaying?: import("react").ReactEventHandler<Element> | undefined;
    onPlayingCapture?: import("react").ReactEventHandler<Element> | undefined;
    onProgress?: import("react").ReactEventHandler<Element> | undefined;
    onProgressCapture?: import("react").ReactEventHandler<Element> | undefined;
    onRateChange?: import("react").ReactEventHandler<Element> | undefined;
    onRateChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onResize?: import("react").ReactEventHandler<Element> | undefined;
    onResizeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onSeeked?: import("react").ReactEventHandler<Element> | undefined;
    onSeekedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onSeeking?: import("react").ReactEventHandler<Element> | undefined;
    onSeekingCapture?: import("react").ReactEventHandler<Element> | undefined;
    onStalled?: import("react").ReactEventHandler<Element> | undefined;
    onStalledCapture?: import("react").ReactEventHandler<Element> | undefined;
    onSuspend?: import("react").ReactEventHandler<Element> | undefined;
    onSuspendCapture?: import("react").ReactEventHandler<Element> | undefined;
    onTimeUpdate?: import("react").ReactEventHandler<Element> | undefined;
    onTimeUpdateCapture?: import("react").ReactEventHandler<Element> | undefined;
    onVolumeChange?: import("react").ReactEventHandler<Element> | undefined;
    onVolumeChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onWaiting?: import("react").ReactEventHandler<Element> | undefined;
    onWaitingCapture?: import("react").ReactEventHandler<Element> | undefined;
    onAuxClick?: import("react").MouseEventHandler<Element> | undefined;
    onAuxClickCapture?: import("react").MouseEventHandler<Element> | undefined;
    onClickCapture?: import("react").MouseEventHandler<Element> | undefined;
    onContextMenu?: import("react").MouseEventHandler<Element> | undefined;
    onContextMenuCapture?: import("react").MouseEventHandler<Element> | undefined;
    onDoubleClick?: import("react").MouseEventHandler<Element> | undefined;
    onDoubleClickCapture?: import("react").MouseEventHandler<Element> | undefined;
    onDrag?: import("react").DragEventHandler<Element> | undefined;
    onDragCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragEnd?: import("react").DragEventHandler<Element> | undefined;
    onDragEndCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragEnter?: import("react").DragEventHandler<Element> | undefined;
    onDragEnterCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragExit?: import("react").DragEventHandler<Element> | undefined;
    onDragExitCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragLeave?: import("react").DragEventHandler<Element> | undefined;
    onDragLeaveCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragOver?: import("react").DragEventHandler<Element> | undefined;
    onDragOverCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragStart?: import("react").DragEventHandler<Element> | undefined;
    onDragStartCapture?: import("react").DragEventHandler<Element> | undefined;
    onDrop?: import("react").DragEventHandler<Element> | undefined;
    onDropCapture?: import("react").DragEventHandler<Element> | undefined;
    onMouseDown?: import("react").MouseEventHandler<Element> | undefined;
    onMouseDownCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseMoveCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOut?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOutCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOver?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOverCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseUp?: import("react").MouseEventHandler<Element> | undefined;
    onMouseUpCapture?: import("react").MouseEventHandler<Element> | undefined;
    onSelect?: import("react").ReactEventHandler<Element> | undefined;
    onSelectCapture?: import("react").ReactEventHandler<Element> | undefined;
    onTouchCancel?: import("react").TouchEventHandler<Element> | undefined;
    onTouchCancelCapture?: import("react").TouchEventHandler<Element> | undefined;
    onTouchEnd?: import("react").TouchEventHandler<Element> | undefined;
    onTouchEndCapture?: import("react").TouchEventHandler<Element> | undefined;
    onTouchMove?: import("react").TouchEventHandler<Element> | undefined;
    onTouchMoveCapture?: import("react").TouchEventHandler<Element> | undefined;
    onTouchStart?: import("react").TouchEventHandler<Element> | undefined;
    onTouchStartCapture?: import("react").TouchEventHandler<Element> | undefined;
    onPointerDown?: import("react").PointerEventHandler<Element> | undefined;
    onPointerDownCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerMove?: import("react").PointerEventHandler<Element> | undefined;
    onPointerMoveCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerUp?: import("react").PointerEventHandler<Element> | undefined;
    onPointerUpCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerCancel?: import("react").PointerEventHandler<Element> | undefined;
    onPointerCancelCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerEnter?: import("react").PointerEventHandler<Element> | undefined;
    onPointerLeave?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOver?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOverCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOut?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOutCapture?: import("react").PointerEventHandler<Element> | undefined;
    onGotPointerCapture?: import("react").PointerEventHandler<Element> | undefined;
    onGotPointerCaptureCapture?: import("react").PointerEventHandler<Element> | undefined;
    onLostPointerCapture?: import("react").PointerEventHandler<Element> | undefined;
    onLostPointerCaptureCapture?: import("react").PointerEventHandler<Element> | undefined;
    onScroll?: import("react").UIEventHandler<Element> | undefined;
    onScrollCapture?: import("react").UIEventHandler<Element> | undefined;
    onWheel?: import("react").WheelEventHandler<Element> | undefined;
    onWheelCapture?: import("react").WheelEventHandler<Element> | undefined;
    onAnimationStart?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationStartCapture?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationEnd?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationEndCapture?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationIteration?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationIterationCapture?: import("react").AnimationEventHandler<Element> | undefined;
    onTransitionEnd?: import("react").TransitionEventHandler<Element> | undefined;
    onTransitionEndCapture?: import("react").TransitionEventHandler<Element> | undefined;
};
export declare function useMenuOption(props?: IUseMenuOptionProps, ref?: Ref<any>): {
    isChecked: boolean | undefined;
    'aria-checked': boolean | undefined;
    onClick: (event: MouseEvent<Element, globalThis.MouseEvent>) => void;
    onFocus: (event: FocusEvent<Element, Element>) => void;
    onMouseEnter: (event: MouseEvent<Element, globalThis.MouseEvent>) => void;
    onMouseMove: (event: MouseEvent<Element, globalThis.MouseEvent>) => void;
    onMouseLeave: (event: MouseEvent<Element, globalThis.MouseEvent>) => void;
    ref: (node: any) => void;
    disabled: boolean | undefined;
    type: "button" | "reset" | "submit";
    id: string;
    tabIndex: number;
    hidden?: boolean | undefined;
    content?: string | undefined;
    style?: import("react").CSSProperties | undefined;
    translate?: "yes" | "no" | undefined;
    slot?: string | undefined;
    title?: string | undefined;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    autoFocus?: boolean | undefined;
    className?: string | undefined;
    contentEditable?: "inherit" | (boolean | "false" | "true") | "plaintext-only" | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: (boolean | "false" | "true") | undefined;
    enterKeyHint?: "next" | "search" | "enter" | "done" | "go" | "previous" | "send" | undefined;
    lang?: string | undefined;
    nonce?: string | undefined;
    spellCheck?: (boolean | "false" | "true") | undefined;
    radioGroup?: string | undefined;
    role?: import("react").AriaRole | undefined;
    about?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    rel?: string | undefined;
    resource?: string | undefined;
    rev?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCapitalize?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "on" | "off" | undefined;
    inputMode?: "none" | "text" | "numeric" | "search" | "tel" | "url" | "email" | "decimal" | undefined;
    is?: string | undefined;
    "aria-activedescendant"?: string | undefined;
    "aria-atomic"?: (boolean | "false" | "true") | undefined;
    "aria-autocomplete"?: "both" | "none" | "inline" | "list" | undefined;
    "aria-braillelabel"?: string | undefined;
    "aria-brailleroledescription"?: string | undefined;
    "aria-busy"?: (boolean | "false" | "true") | undefined;
    "aria-colcount"?: number | undefined;
    "aria-colindex"?: number | undefined;
    "aria-colindextext"?: string | undefined;
    "aria-colspan"?: number | undefined;
    "aria-controls"?: string | undefined;
    "aria-current"?: boolean | "page" | "false" | "true" | "time" | "step" | "location" | "date" | undefined;
    "aria-describedby"?: string | undefined;
    "aria-description"?: string | undefined;
    "aria-details"?: string | undefined;
    "aria-disabled"?: (boolean | "false" | "true") | undefined;
    "aria-dropeffect"?: "none" | "copy" | "move" | "link" | "execute" | "popup" | undefined;
    "aria-errormessage"?: string | undefined;
    "aria-expanded"?: (boolean | "false" | "true") | undefined;
    "aria-flowto"?: string | undefined;
    "aria-grabbed"?: (boolean | "false" | "true") | undefined;
    "aria-haspopup"?: boolean | "listbox" | "grid" | "menu" | "false" | "true" | "dialog" | "tree" | undefined;
    "aria-hidden"?: (boolean | "false" | "true") | undefined;
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
    "aria-keyshortcuts"?: string | undefined;
    "aria-label"?: string | undefined;
    "aria-labelledby"?: string | undefined;
    "aria-level"?: number | undefined;
    "aria-live"?: "off" | "assertive" | "polite" | undefined;
    "aria-modal"?: (boolean | "false" | "true") | undefined;
    "aria-multiline"?: (boolean | "false" | "true") | undefined;
    "aria-multiselectable"?: (boolean | "false" | "true") | undefined;
    "aria-orientation"?: "horizontal" | "vertical" | undefined;
    "aria-owns"?: string | undefined;
    "aria-placeholder"?: string | undefined;
    "aria-posinset"?: number | undefined;
    "aria-pressed"?: boolean | "mixed" | "false" | "true" | undefined;
    "aria-readonly"?: (boolean | "false" | "true") | undefined;
    "aria-relevant"?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
    "aria-required"?: (boolean | "false" | "true") | undefined;
    "aria-roledescription"?: string | undefined;
    "aria-rowcount"?: number | undefined;
    "aria-rowindex"?: number | undefined;
    "aria-rowindextext"?: string | undefined;
    "aria-rowspan"?: number | undefined;
    "aria-selected"?: (boolean | "false" | "true") | undefined;
    "aria-setsize"?: number | undefined;
    "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
    "aria-valuemax"?: number | undefined;
    "aria-valuemin"?: number | undefined;
    "aria-valuenow"?: number | undefined;
    "aria-valuetext"?: string | undefined;
    children?: import("react").ReactNode;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: import("react").ClipboardEventHandler<Element> | undefined;
    onCopyCapture?: import("react").ClipboardEventHandler<Element> | undefined;
    onCut?: import("react").ClipboardEventHandler<Element> | undefined;
    onCutCapture?: import("react").ClipboardEventHandler<Element> | undefined;
    onPaste?: import("react").ClipboardEventHandler<Element> | undefined;
    onPasteCapture?: import("react").ClipboardEventHandler<Element> | undefined;
    onCompositionEnd?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionEndCapture?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionStart?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionStartCapture?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionUpdate?: import("react").CompositionEventHandler<Element> | undefined;
    onCompositionUpdateCapture?: import("react").CompositionEventHandler<Element> | undefined;
    onFocusCapture?: import("react").FocusEventHandler<Element> | undefined;
    onBlur?: import("react").FocusEventHandler<Element> | undefined;
    onBlurCapture?: import("react").FocusEventHandler<Element> | undefined;
    onChange?: import("react").FormEventHandler<Element> | undefined;
    onChangeCapture?: import("react").FormEventHandler<Element> | undefined;
    onBeforeInput?: import("react").FormEventHandler<Element> | undefined;
    onBeforeInputCapture?: import("react").FormEventHandler<Element> | undefined;
    onInput?: import("react").FormEventHandler<Element> | undefined;
    onInputCapture?: import("react").FormEventHandler<Element> | undefined;
    onReset?: import("react").FormEventHandler<Element> | undefined;
    onResetCapture?: import("react").FormEventHandler<Element> | undefined;
    onSubmit?: import("react").FormEventHandler<Element> | undefined;
    onSubmitCapture?: import("react").FormEventHandler<Element> | undefined;
    onInvalid?: import("react").FormEventHandler<Element> | undefined;
    onInvalidCapture?: import("react").FormEventHandler<Element> | undefined;
    onLoad?: import("react").ReactEventHandler<Element> | undefined;
    onLoadCapture?: import("react").ReactEventHandler<Element> | undefined;
    onError?: import("react").ReactEventHandler<Element> | undefined;
    onErrorCapture?: import("react").ReactEventHandler<Element> | undefined;
    onKeyDown?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyDownCapture?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyPress?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyPressCapture?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyUp?: import("react").KeyboardEventHandler<Element> | undefined;
    onKeyUpCapture?: import("react").KeyboardEventHandler<Element> | undefined;
    onAbort?: import("react").ReactEventHandler<Element> | undefined;
    onAbortCapture?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlay?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlayCapture?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlayThrough?: import("react").ReactEventHandler<Element> | undefined;
    onCanPlayThroughCapture?: import("react").ReactEventHandler<Element> | undefined;
    onDurationChange?: import("react").ReactEventHandler<Element> | undefined;
    onDurationChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onEmptied?: import("react").ReactEventHandler<Element> | undefined;
    onEmptiedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onEncrypted?: import("react").ReactEventHandler<Element> | undefined;
    onEncryptedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onEnded?: import("react").ReactEventHandler<Element> | undefined;
    onEndedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedData?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedDataCapture?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedMetadata?: import("react").ReactEventHandler<Element> | undefined;
    onLoadedMetadataCapture?: import("react").ReactEventHandler<Element> | undefined;
    onLoadStart?: import("react").ReactEventHandler<Element> | undefined;
    onLoadStartCapture?: import("react").ReactEventHandler<Element> | undefined;
    onPause?: import("react").ReactEventHandler<Element> | undefined;
    onPauseCapture?: import("react").ReactEventHandler<Element> | undefined;
    onPlay?: import("react").ReactEventHandler<Element> | undefined;
    onPlayCapture?: import("react").ReactEventHandler<Element> | undefined;
    onPlaying?: import("react").ReactEventHandler<Element> | undefined;
    onPlayingCapture?: import("react").ReactEventHandler<Element> | undefined;
    onProgress?: import("react").ReactEventHandler<Element> | undefined;
    onProgressCapture?: import("react").ReactEventHandler<Element> | undefined;
    onRateChange?: import("react").ReactEventHandler<Element> | undefined;
    onRateChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onResize?: import("react").ReactEventHandler<Element> | undefined;
    onResizeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onSeeked?: import("react").ReactEventHandler<Element> | undefined;
    onSeekedCapture?: import("react").ReactEventHandler<Element> | undefined;
    onSeeking?: import("react").ReactEventHandler<Element> | undefined;
    onSeekingCapture?: import("react").ReactEventHandler<Element> | undefined;
    onStalled?: import("react").ReactEventHandler<Element> | undefined;
    onStalledCapture?: import("react").ReactEventHandler<Element> | undefined;
    onSuspend?: import("react").ReactEventHandler<Element> | undefined;
    onSuspendCapture?: import("react").ReactEventHandler<Element> | undefined;
    onTimeUpdate?: import("react").ReactEventHandler<Element> | undefined;
    onTimeUpdateCapture?: import("react").ReactEventHandler<Element> | undefined;
    onVolumeChange?: import("react").ReactEventHandler<Element> | undefined;
    onVolumeChangeCapture?: import("react").ReactEventHandler<Element> | undefined;
    onWaiting?: import("react").ReactEventHandler<Element> | undefined;
    onWaitingCapture?: import("react").ReactEventHandler<Element> | undefined;
    onAuxClick?: import("react").MouseEventHandler<Element> | undefined;
    onAuxClickCapture?: import("react").MouseEventHandler<Element> | undefined;
    onClickCapture?: import("react").MouseEventHandler<Element> | undefined;
    onContextMenu?: import("react").MouseEventHandler<Element> | undefined;
    onContextMenuCapture?: import("react").MouseEventHandler<Element> | undefined;
    onDoubleClick?: import("react").MouseEventHandler<Element> | undefined;
    onDoubleClickCapture?: import("react").MouseEventHandler<Element> | undefined;
    onDrag?: import("react").DragEventHandler<Element> | undefined;
    onDragCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragEnd?: import("react").DragEventHandler<Element> | undefined;
    onDragEndCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragEnter?: import("react").DragEventHandler<Element> | undefined;
    onDragEnterCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragExit?: import("react").DragEventHandler<Element> | undefined;
    onDragExitCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragLeave?: import("react").DragEventHandler<Element> | undefined;
    onDragLeaveCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragOver?: import("react").DragEventHandler<Element> | undefined;
    onDragOverCapture?: import("react").DragEventHandler<Element> | undefined;
    onDragStart?: import("react").DragEventHandler<Element> | undefined;
    onDragStartCapture?: import("react").DragEventHandler<Element> | undefined;
    onDrop?: import("react").DragEventHandler<Element> | undefined;
    onDropCapture?: import("react").DragEventHandler<Element> | undefined;
    onMouseDown?: import("react").MouseEventHandler<Element> | undefined;
    onMouseDownCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseMoveCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOut?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOutCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOver?: import("react").MouseEventHandler<Element> | undefined;
    onMouseOverCapture?: import("react").MouseEventHandler<Element> | undefined;
    onMouseUp?: import("react").MouseEventHandler<Element> | undefined;
    onMouseUpCapture?: import("react").MouseEventHandler<Element> | undefined;
    onSelect?: import("react").ReactEventHandler<Element> | undefined;
    onSelectCapture?: import("react").ReactEventHandler<Element> | undefined;
    onTouchCancel?: import("react").TouchEventHandler<Element> | undefined;
    onTouchCancelCapture?: import("react").TouchEventHandler<Element> | undefined;
    onTouchEnd?: import("react").TouchEventHandler<Element> | undefined;
    onTouchEndCapture?: import("react").TouchEventHandler<Element> | undefined;
    onTouchMove?: import("react").TouchEventHandler<Element> | undefined;
    onTouchMoveCapture?: import("react").TouchEventHandler<Element> | undefined;
    onTouchStart?: import("react").TouchEventHandler<Element> | undefined;
    onTouchStartCapture?: import("react").TouchEventHandler<Element> | undefined;
    onPointerDown?: import("react").PointerEventHandler<Element> | undefined;
    onPointerDownCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerMove?: import("react").PointerEventHandler<Element> | undefined;
    onPointerMoveCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerUp?: import("react").PointerEventHandler<Element> | undefined;
    onPointerUpCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerCancel?: import("react").PointerEventHandler<Element> | undefined;
    onPointerCancelCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerEnter?: import("react").PointerEventHandler<Element> | undefined;
    onPointerLeave?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOver?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOverCapture?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOut?: import("react").PointerEventHandler<Element> | undefined;
    onPointerOutCapture?: import("react").PointerEventHandler<Element> | undefined;
    onGotPointerCapture?: import("react").PointerEventHandler<Element> | undefined;
    onGotPointerCaptureCapture?: import("react").PointerEventHandler<Element> | undefined;
    onLostPointerCapture?: import("react").PointerEventHandler<Element> | undefined;
    onLostPointerCaptureCapture?: import("react").PointerEventHandler<Element> | undefined;
    onScroll?: import("react").UIEventHandler<Element> | undefined;
    onScrollCapture?: import("react").UIEventHandler<Element> | undefined;
    onWheel?: import("react").WheelEventHandler<Element> | undefined;
    onWheelCapture?: import("react").WheelEventHandler<Element> | undefined;
    onAnimationStart?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationStartCapture?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationEnd?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationEndCapture?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationIteration?: import("react").AnimationEventHandler<Element> | undefined;
    onAnimationIterationCapture?: import("react").AnimationEventHandler<Element> | undefined;
    onTransitionEnd?: import("react").TransitionEventHandler<Element> | undefined;
    onTransitionEndCapture?: import("react").TransitionEventHandler<Element> | undefined;
};
export declare function useMenuOptionGroup(props?: IUseMenuOptionGroupProps): {
    children: import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>>[];
};
export declare function useMenuState(): {
    isOpen: boolean;
    onClose: () => void;
};
